### ISSUE TITLE
USP E2E

### ISSUE THREAD

**Issue by jm555** [BroadbandForum/obuspa#1]
the agent can be used in E2E Session Context? if yes, where in the src code we choose the port, in order to open it in agent for socket?

**Comment by holme-r** [comment]
Sorry but E2E Session Context is not yet supported.

**Comment by johnblackford** [comment]
jm555, thanks for your question and support.  As Richard mentioned in the previous comment, the E2E Session Context support is not there yet, but it is a feature that we plan on implementing.

**Comment by jm555** [comment]
thanks for your answer, there is a code for controller in order to test the agent ?

**Comment by johnblackford** [comment]
jm55, we are working on a USP controller that could be used for testing purposes.  Please keep monitoring the project for this.

**Comment by johnblackford** [comment]
@jm555, the test controller is now available here: https://github.com/BroadbandForum/obuspa-test-controller 

I'll close this ticket out now.

Thank you.

**Comment by johnblackford** [comment]
@jm555, we now have a published roadmap for the  project that details when the E2E context feature will be included.  Please see here: https://github.com/BroadbandForum/obuspa/wiki/Roadmap
