### ISSUE TITLE
Is there a mailing list? Where does project participants communicate?

### ISSUE THREAD

**Issue by aciliketcap** [BroadbandForum/obuspa#10]
Hello, in CONTRIBUTING.md a mailing list is mentioned but I couldn't find a mailing list which I can subscribe to. ( I think there was one for prplwrt somewhere but link was broken.)

Can you provide a link for the mailing list (if there is one) in the wiki so that we can track the development of the project and ask simpler questions like how to make something work or if there is plan to implement some feature or ask about the release date etc. there instead of opening an issue on GitHub.

If there is no mailing list where can we communicate with project participants? Is opening GitHub issues the only way?

Thank you very much and congratulations on first two releases.

**Comment by johnblackford** [comment]
@aciliketcap, thank you for bringing the missing details to our attention.  The mailing list is obuspa-info@broadband-forum.org

I'll get the wiki updated with this information as well.

**Comment by aciliketcap** [comment]
Thank you very much for the reply :+1:
