### ISSUE TITLE
Problem with connection to MQTT Broker via TLS

### ISSUE THREAD

**Issue by Wonderjack996** [BroadbandForum/obuspa#101]
Hi. I'm trying to connect to an MQTT broker hosted on port 8883, that need SSL for connection. I've specified the broker address, username and password in mqtt factory reset file, specifying as TransportProtocol TLS. I've also create a self signed certificate file, containing also the private key, passed with the -a option. I got the error LoadClientCert: SSL_CTX_use_certificate() failed, and don't know why. Any ideas? Thanks.
Here my certificate (the private key is only a test):
-----BEGIN CERTIFICATE-----
MIIDMjCCAhoCAQEwDQYJKoZIhvcNAQELBQAwgaExCzAJBgNVBAYTAklUMQ4wDAYD
VQQIDAVNaWxhbjEUMBIGA1UEBwwLQ2FzdGVsbGFuemExEzARBgNVBAoMClVuaXZl
cnNpdHkxEDAOBgNVBAsMB0JpY29jY2ExGTAXBgNVBAMMEGdpYWNvbW9zYXZhenpp
Q0ExKjAoBgkqhkiG9w0BCQEWG2cuc2F2YXp6aTFAY2FtcHVzLnVuaW1pYi5pdDAe
Fw0yNDAxMTAxNTU0MDZaFw0yNDA0MDkxNTU0MDZaMIGfMQswCQYDVQQGEwJJVDEO
MAwGA1UECAwFTWlsYW4xFDASBgNVBAcMC0Nhc3RlbGxhbnphMRMwEQYDVQQKDApV
bml2ZXJzaXR5MRAwDgYDVQQLDAdCaWNvY2NhMRcwFQYDVQQDDA5naWFjb21vc2F2
YXp6aTEqMCgGCSqGSIb3DQEJARYbZy5zYXZhenppMUBjYW1wdXMudW5pbWliLml0
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDDmGRICJkimJwSwIZXBXKsiRfO
vyyCfxNf8lDQFhKXQpp0Uth9R87TLzq+YcuKXQzGv9+FqXB565rkLu5s+nruOJiE
kWF1Ac1WF6H1zEm0kY7dZ4DzTvphkBT2S4qhcqrtIOcUnlycdmT1i7jdiyUOw2o/
hkO3RerLinYleJ/RjQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQACoTsnBxm3I4OC
HYCL7HJB27OT6/6k0p9JlhSIvZga0pGAoVCLCIRVulGlfonraqPQhDmJOYbST0Un
d6t+mrJ/KF3T6IWsNf26yfdXSe7oEhFiHc26OhVJDljbKNfSqFspAkFOKjH/nKUI
PparmF7tV0AkJP8GEGE1zIycr0n9iR3gNsncS+CzcgZlwC3wS1R2pZeyzCpKodXN
OjZFJWqs3q6R5u6Fssv1vfYYAiC1UrozAEXvH7VMqysg6q4ylSRsqCThnuQrejFk
P4xXuuHEpbMjmdExHmB6z9dz0e7oooDKEsfozEp9TjkdnvGfodG196ExPPl15h68
+AQmsLr0
-----END CERTIFICATE-----
-----BEGIN RSA PRIVATE KEY-----
.....
-----END RSA PRIVATE KEY-----

**Comment by holme-r** [comment]
I'm not seeing any error being returned by OpenSSL when I tried your cert in my environment.
Perhaps this is an issue with the options configured for your OpenSSL library, or an issue related to OpenSSL version ? This seems most likely as the error is being returned by OpenSSL.

By the way, were you intending to use the -a or the -t option ?
* The -t option specifies the CA certs in OBUSPA's trust store. This needs to include the CA cert which signed the server cert (of the MQTT Broker that you're connecting to). This is just a public cert - no private key.
* The -a option is for specifying a client certificate. This would be a cert which is specific to the device and which was signed by one of the CA certs installed in the trust store of the MQTT Broker. This includes both the public and private parts of the cert.
You must specify the -t option when using TLS but client certs (-a) are optional.

**Comment by Wonderjack996** [comment]
Thank you so much. Now I've undestand the difference between the two option. My problem was related to the fact that i was not passing the correct server certificate to obuspa. I've removed the private key from the comment for much security.
