### ISSUE TITLE
Queries Regarding Custom Node Definitions for TR-069 Data Model

### ISSUE THREAD

**Issue by Luck19921** [BroadbandForum/obuspa#102]
Hi Everyone,

I am writing to seek clarification on certain aspects related to custom node definitions in the context of TR-069 Data Model.

Q1: If the Type attribute of a node has been modified and differs from the Spec, should it still be considered a standard node?
Example: Type int(0:6535) => (1:6535)

Q2: If the Write attribute of a node has changed from ReadOnly to Read/Write, should it be regarded as a standard node?
Example: ReadOnly => Read/Write

Q3: Conversely, if the Write attribute of a node has been altered from Write to ReadOnly, should it still be considered a standard node?
Example: Read/Write => ReadOnly

Your insights on these matters will be highly valuable in ensuring adherence to the standard specifications. I appreciate your prompt attention to these queries and look forward to your guidance.

Thank you for your time and assistance.

**Comment by holme-r** [comment]
This is not really a query for OBUSPA, but more of a query for BBF.
I can't give an official answer, but in my experience, if the parameter is representing the same quantity then even if the aspects you point out are different from the spec, then it is still regarded as a standard node.

**Comment by wlupton** [comment]
Thanks @holme-r. @Luck19921, I note that you also sent this question to the help@broadband-forum.org email list, and we'll ensure that you receive a response via that channel.

**Comment by Luck19921** [comment]
Hi @holme-r ,

I will try to contact with the BBF and query these questions of spec.

Thanks for your advice and assistance.
