### ISSUE TITLE
OnBoardRequest sent by obuspa

### ISSUE THREAD

**Issue by chen0627** [BroadbandForum/obuspa#103]
Hi Team,

I notice that obuspa just establishes a session to controller but it would not send an OnBoardRequest message or a Boot/Wakeup event to controller.

I have to execute the following command when I configure device after a factory reset. 
    obuspa -c operate "Device.LocalAgent.Controller.1.SendOnBoardRequest()"

Is there a way for obuspa to send these kind of message spontaneously when the session is established? 

BTW, I am using protocol WebSocket on obuspa version 7.0.0. 

Thank you.

**Comment by holme-r** [comment]
OBUSPA can sent a Boot! event, but you need to setup a subscription for the event. This would normally be done in your factory reset configuration.
OBUSPA also sends USP Connect records (https://usp.technology/specification/index.html#sec:connect-and-disconnect-record-types).
SendOnBoardRequest() is a USP Command that a USP Controller can invoke on the USP Agent. It's not intended that a USP Agent self-invokes the command.
