### ISSUE TITLE
Data model ARRIS COM obj

### ISSUE THREAD

**Issue by leandrofars** [BroadbandForum/obuspa#105]
Hello,

I'm using obuspa with factory reset params via mqtt, by default it comes with Device.BulkData.Profile.*.X_ARRIS-COM_Status parameter, which i couldn't find at  tr-181 data model.
Got it using SupportedDataModel message:

![image](https://github.com/BroadbandForum/obuspa/assets/83298718/74345895-8ca0-4527-9411-82375b9d998c)

![image](https://github.com/BroadbandForum/obuspa/assets/83298718/d923d66a-fb2b-428c-ae9d-b6ab4a620bbb)

**Comment by holme-r** [comment]
This is a vendor extension parameter which has the same meaning as Device.BulkData.Status but applies it to the individual profile, rather than all profiles.
