### ISSUE TITLE
Microsoft Windows support

### ISSUE THREAD

**Issue by ajsb85** [BroadbandForum/obuspa#112]
Dearest.
Any plan to build the agent for MacOS or Windows in the future?
Best regards.

**Comment by johnblackford** [comment]
@ajsb85  - could you expand upon the use cases here?

**Comment by ajsb85** [comment]
We use Windows 10 IoT Enterprise in some devices.
We would love to manage the custom IoT features (Example: modify the CAN bus settings using USP)
Using the Obuspa as based Agent for our development.
