### ISSUE TITLE
USP_Service multiple Object Registrations

### ISSUE THREAD

**Issue by CSalaza73** [BroadbandForum/obuspa#113]
Hello,
We have implemented USP Broker/Service feature. We have a use case where we want one service to hold multiple functinalities, meaning different Data Model Object with parameters. The documentation has the command line with -R registration for something such as "Device.IP.Diagnostics.". Is it possible to have multiple data model object/parameters?

For example can we do 
obuspa -f usp_service.db -s /tmp/service_cli -p -v 4 -r /usr/bin/service_reset.txt -R "Device.IP.Diagnostics." "Device.WiFi.AccesPoint."

Or is each USP Service portion only allow to -R register one data model object path? If we want to register Device.IP.Diagnostics with Device.WiFi.AccessPoint. this will not be possible under one service? We would need two separate services?

**Comment by holme-r** [comment]
Pass a comma separated list after -R, if you want to register multiple data model elements e.g.
obuspa -f usp_service.db -s /tmp/service_cli -p -v 4 -r /usr/bin/service_reset.txt -R "Device.IP.Diagnostics., Device.WiFi.AccesPoint."

**Comment by CSalaza73** [comment]
Thank you. We tested and seems to be working. Thank you for the quick turnaround.
