### ISSUE TITLE
obuspa sending subscribe packet again after receiving suback with Unspecified error(128)

### ISSUE THREAD

**Issue by Saravana1088** [BroadbandForum/obuspa#115]
Hello,

While running CDRouter USP Conformance mandatory test in obuspa 9.0.0, usp_conformance_11_11 case failed. 

The DUT sends a SUBSCRIBE packet to which the controller sends a Suback with "Unspecified error (128)". According to [R-MQTT.17](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fusp.technology%2Fspecification%2Findex.html%23r-mqtt.17&data=05%7C02%7Cs.1.saravanakumar%40nokia.com%7C8c743ae81e834526f1d708dcf5113cb1%7C5d4717519675428d917b70f44f9630b0%7C0%7C0%7C638654701656456592%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=4ZW3V9qQu6rINXb%2FfnnDlai2N4Td78RFAL6ZJ6lXexE%3D&reserved=0) of the USP Specification, the DUT should send no more PUBLISH packets once the SUBSCRIBE has failed. 

Immediately after the Suback is received, the DUT sends an MQTT packet containing SUBSCRIBE, PUBLISH, & PUBLISH control messages. The DUT should not be sending any of these packets, since the SUBSCRIBE has already failed. Additionally, it seems odd for the DUT to send a PUBLISH control message in the same packet with a SUBSCRIBE since it has not received a successful SUBACK response yet. 

Because of this behavior the test case got failed. I have confirmed the same behavior with the plain obuspa-9.0.0 code without vendor changes.

Attached the CDRouter logs here [usp_conformance_11_11_failure_log.txt](https://github.com/user-attachments/files/17642766/usp_conformance_11_11_failure_log.txt)

Kindly confirm if this is an obuspa issue in latest 9.0.0 code.

**Comment by holme-r** [comment]
This is an issue in OBUSPA. We have opened a ticket and have started work on a fix.

**Comment by Saravana1088** [comment]
Thanks. Could you please let me know whether the fix can be available in 9.0.4.

**Comment by Saravana1088** [comment]
Got it. Thanks!

**Comment by holme-r** [comment]
Closing as the fix is available now in v9.0.4, which has been released.
