### ISSUE TITLE
Missing definitions when compiling with 9.0.0

### ISSUE THREAD

**Issue by vineethshankar28** [BroadbandForum/obuspa#116]
I started compiling with obuspa version 9.0.0
However, I got undeclared error for below symbols

ROLE_UDS
MAX_UDS_SERVERS 
MAX_USP_SERVICES 
MAX_UDS_FRAME_PAYLOAD_LEN 
MAX_CTRUST_ROLES 
ROLE_TRUST_STORE_DEFAULT
MAX_MSG_ID_LEN 
GROUP_GET_CHUNK_SIZE 
MAX_ENDPOINT_ID_LEN 
ROLE_FULL_ACCESS 
USP_LOG_MAXLEN 
MQTT_CONNECT_TIMEOUT 
ROLE_UNTRUSTED 

Why are they missing/not defined?
What should be their default values?

**Comment by vineethshankar28** [comment]
I gave some random default values and compiled
Even though connection to controller using mqtt is successful, I am facing below error in logs

`header {
  msg_id: "6736ffa393e74180e7343350"
  msg_type: ERROR
}
body {
  error {
    err_code: 7006
    err_msg: "GROUP_SET_VECTOR_Add: No permission to write to Device.MQTT.Client.1.ClientID"
    param_errs {
      param_path: "Device.MQTT.Client.1.ClientID"
      err_code: 7006
      err_msg: "GROUP_SET_VECTOR_Add: No permission to write to Device.MQTT.Client.1.ClientID"
    }
    param_errs {
      param_path: "Device.MQTT.Client.1.Username"
      err_code: 7006
      err_msg: "GROUP_SET_VECTOR_Add: No permission to write to Device.MQTT.Client.1.Username"
    }
    param_errs {
      param_path: "Device.MQTT.Client.1.Password"
      err_code: 7006
      err_msg: "GROUP_SET_VECTOR_Add: No permission to write to Device.MQTT.Client.1.Password"
    }
    param_errs {
      param_path: "Device.LocalAgent.Controller.1.MTP.1.MQTT.Topic"
      err_code: 7006
      err_msg: "GROUP_SET_VECTOR_Add: No permission to write to Device.LocalAgent.Controller.1.MTP.1.MQTT.Topic"
    }
  }
}
`

How do I resolve this?

**Comment by anderewrey** [comment]
All these defines come from https://github.com/BroadbandForum/obuspa/blob/master/src/vendor/vendor_defs.h

and filled with a "by-default" value.

**Comment by holme-r** [comment]
Using the default values in vendor_defs.h should also fix your "No permission to write to Device.MQTT.Client.1.ClientID" error. I'm guessing that you've added something to your build process which modifies vendor_defs.h, but that this is going wrong and deleting various defines from the file.

**Comment by vineethshankar28** [comment]
Incorporated the missing #defines from vendor_defs.h
However, no permission to write these below parameters is not resolved
Device.MQTT.Client.1.ClientID
Device.MQTT.Client.1.Username
Device.MQTT.Client.1.Password
Device.LocalAgent.Controller.1.MTP.1.MQTT.Topic

> # UspPa_9_0 -c get "Device.MQTT.Client.1.Password"
> Device.MQTT.Client.1.Password =>
> # UspPa_9_0 -c get "Device.MQTT.Client.1.Username"
> Device.MQTT.Client.1.Username => NewDevice-IOT
> # UspPa_9_0 -c get "Device.MQTT.Client.1.ClientID"
> Device.MQTT.Client.1.ClientID => 0050F1-PUMA8-PKE3310_009
> # UspPa_9_0 -c get "Device.LocalAgent.Controller.1.MTP.1.MQTT.Topic"
> Device.LocalAgent.Controller.1.MTP.1.MQTT.Topic => usp/device/initialize

I even deleted the usp_dm_comps.conf, usp_dm_objs.conf, usp_dm_params.conf and deleted /nvram/usp-pa.db

What is the impact of this error? I am able to perform GET operation from controller and able to see the response in the controller logs. However, I do not see the request/response logs from the usp agent.

**Comment by holme-r** [comment]
OK I understand now. You should have said that you were trying to get OBUSPAv9 working with RDK.
The official integration of OBUSPAv9 into RDK hasn't been done yet. I recommend you wait until this has been done officially. You should only attempt it if you are able to figure out the issues yourself.

**Comment by vineethshankar28** [comment]
OK, I will try to see if I can fix this.
Appreciate your inputs. Thank you!

**Comment by vineethshankar28** [comment]
Can I get a sample usp_factory_reset.conf to test MQTT on OBUSPAv9?

**Comment by holme-r** [comment]
Closing, as the original issue seems to be resolved and there has been no more discussion. It can always be reopened if necessary.
