### ISSUE TITLE
OnBoardRequest Notification and Timer! Event Support 

### ISSUE THREAD

**Issue by shanthakumarks** [BroadbandForum/obuspa#14]
Hi ,

We found that obuspa does not have support for OnBoardRequest Notification and Timer Event yet. As an integrator, should I expect these functionalities to be part of obuspa's core functionality (src/core)? or is it something expected to be implemented in the vendor hooks ( src/vendor) by the integrator who is using the obuspa source code ?  

Please let me know if this functionality is planned to be implemented as obuspa core functionality and planned to be released in near future ? This will help us to avoid redundant implementation.

Thanks,
Shantha Kumar.

**Comment by shanthakumarks** [comment]
Just checking if this question was overlooked ..  Do we have any update on this ?

**Comment by holme-r** [comment]
We are going to put these features in our next release, Release 4. Please keep an eye on [https://github.com/BroadbandForum/obuspa/wiki/Roadmap] for updates to the contents and timing of the next release.
