### ISSUE TITLE
Question About the ControllerTrust

### ISSUE THREAD

**Issue by ahmedarif193** [BroadbandForum/obuspa#18]
Hello Team,

I have a few questions about the controllerTrust functionality:

- do you have any planning for the delivery date? in the roadmap, it said that it will be available in Q1 and we are already in Q2.

-does this functionality will manage CA and challenges with the controller? if not, do you have any references to use it?

thank you.

**Comment by johnblackford** [comment]
@ahmedarif193, yes Release 4 has been slightly delayed.  We are now expecting release 4 to be complete by the end of this month.  Release 4 will contain more ControllerTrust features, including the Challenge/Response mechanism.
