### ISSUE TITLE
Has anybody created or come across a Dockerfile for build obuspa?

### ISSUE THREAD

**Issue by aramf** [BroadbandForum/obuspa#19]
We are experimenting with different ways to build/deploy obuspa on platforms where the base operating system comes from a different vendor.

Wondering if anyone has created a Dockerfile for building this code, so as to not reinvent the wheel.

If not, I can take a stab at it. It should be pretty straightforward, until you add your vendor code for device configurations. :-)

**Comment by holme-r** [comment]
We have been working on a Dockerfile for release 4.0, but I'm not sure how suitable it will be for your needs, as it is fairly simple. In the meantime, I suggest going ahead and creating your own Dockerfile.
