### ISSUE TITLE
ERROR : connect failed 

### ISSUE THREAD

**Issue by Marwa-BAHLOUL** [BroadbandForum/obuspa#2]
if I run obuspa -c get "Device.DeviceInfo." 
I get an error : HandleCliCommandRemotely(178): connect failed : (err=111) Connection refused

**Comment by holme-r** [comment]
Marwa-BAHLOUL, thanks for your question and support.
The 'obuspa -c get' command queries another running instance of obuspa (the instance running as a daemon). It does this by connecting to a Unix domain socket that the daemon instance is listening to.
If you get this error, either there is not a daemon instance of obuspa running, or the daemon instance is running with different permissions than the 'obuspa -c get' command. For example, maybe the daemon instance is running as the root user, whilst 'obuspa -c get' is invoked by an ordinary user (fix: use 'sudo obuspa -c get' instead).

**Comment by Marwa-BAHLOUL** [comment]
think you, also with 'sudo obuspa -c get' I get the same error

**Comment by Marwa-BAHLOUL** [comment]
thank you, also with 'sudo obuspa -c get' I get the same error

**Comment by johnblackford** [comment]
Marwa-BAHLOUL, obuspa has to be running before you do a 'obuspa -c get' command.  So essentially you run obuspa (and keep it running) and then you use obuspa again as a stand-alone "-c get" command.  Does that help?

**Comment by johnblackford** [comment]
Looks like this has been resolved, closing
