### ISSUE TITLE
Bulkdata Collection using USPNotif throws console error related to HTTP URL

### ISSUE THREAD

**Issue by shanthakumarks** [BroadbandForum/obuspa#20]
Hi,

USP Agent throws an error _"bulkdata_platform_get_profile_control_params: Profile 1 started but it's URL has not been setup"_ in the USP Agent console when Bulkadata collection is configured to use USPNotif as Protocol.  The functionality still works fine though. It  just reports an error that is related to the HTTP URL though Bulk data profile is configured to USPNotif. 

I have pasted the console error below .

#/usr/bin# obuspa -p -v 4 
DATABASE_Init: Opening database /usr/local/etc/usp.db
.
.
LoadClientCert: Not using a device certificate for connections
DEVICE_STOMP_Start: WARNING: No instances in Device.STOMP.Connection
**bulkdata_platform_get_profile_control_params: Profile 1 started but it's URL has not been setup**

**Comment by holme-r** [comment]
Thanks for reporting this issue. It was not intended that the error message was output when USPEventNotif is used. We will fix it in the next release.

**Comment by holme-r** [comment]
Closing as fixed in release 4.1.
