### ISSUE TITLE
The controller subscribes to obj delete, but does not receive a message

### ISSUE THREAD

**Issue by time-beyond** [BroadbandForum/obuspa#21]
When the controller subscribes to objectdeletion (Device.IP.Interface.*.IPv4Address.*.).
![image](https://user-images.githubusercontent.com/54758785/124243406-71520780-db50-11eb-8a89-9c11f16469eb.png)

At first, the data in the database.
![image](https://user-images.githubusercontent.com/54758785/124243079-030d4500-db50-11eb-9d05-fff6a8db536d.png)
After deleting Device.IP.Interface.3.
![image](https://user-images.githubusercontent.com/54758785/124243200-2932e500-db50-11eb-8e33-6d11412e499e.png)
But obuspa didn't send a notification to the controller. Only when 'Device.IP.Interface.3.IPv4Address.1' is deleted directly, there will be a notification

**Comment by holme-r** [comment]
Does the table implementation use a refresh_instances callback, or Is deletion being signalled directly by calling USP_SIGNAL_ObjectDeleted() ?
Is this occurring on OBUSPA v4.0 release ?
Thanks.

**Comment by time-beyond** [comment]
We didn't use USP_SIGNAL_ObjectDeleted and refresh_ Instances callback . We use your default notification mechanism, but when the parent node is deleted, there is no notification for the child node's subscription

**Comment by time-beyond** [comment]
Previously, we used obuspa V3.0 release, but the above situation occurred, so I would like to know if you have any changes in 4.0

**Comment by time-beyond** [comment]
I still have this problem with version 4.0.

**Comment by time-beyond** [comment]
ok，thank you for your help

**Comment by time-beyond** [comment]
This problem is caused by the value of path in function DeleteChildParams_MultiInstanceObject being modified by function DeleteChildParams.

**Comment by holme-r** [comment]
Closing as fixed in release 4.1.
