### ISSUE TITLE
USP Get response resolved_path return differently when read one parameter

### ISSUE THREAD

**Issue by nmurugesan** [BroadbandForum/obuspa#27]
Hi,
We are giving GET request with below payload
{
    "header": {
        "msgId": "1234",
        "msgType": "GET"
    },
    "body": {
        "request": {
            "get": {
                "param_paths": [
                    "Device.WiFi.AccessPoint.*.Security.",
                    "Device.WiFi.AccessPoint.*.Security.ModeEnabled",
                    "Device.WiFi.AccessPoint.*.Alias"
                ]
            }
        }
    }
}
The response we got is below
{
    "header": {
        "msgId": "1234",
        "msgType": "GET_RESP"
    },
    "body": {
        "response": {
            "getResp": {
                "reqPathResults": [
                    {
                        "requestedPath": "Device.WiFi.AccessPoint.*.Security.",
                        "resolvedPathResults": [
                            {

                                "resolvedPath": "Device.WiFi.AccessPoint.1.Security.",

                                "resultParams": {

                                    "ModeEnabled": "WPA2-Personal",

                                    "EncryptionMode": "AES",

                                    "KeyPassphrase": "timetopawnl0l"

                                }
                            }
                        ]
                    },
                    **{
                        "requestedPath": "Device.WiFi.AccessPoint.*.Security.ModeEnabled",
                        "resolvedPathResults": [
                            {
                                "resolvedPath": "Device.WiFi.AccessPoint.1.",
                                "resultParams": {
                                    "Security.ModeEnabled": "WPA2-Personal"
                                }
                            }
                        ]
                    }**,
                    {
                        "requestedPath": "Device.WiFi.AccessPoint.*.Alias",
                        "resolvedPathResults": [
                            {
                                "resolvedPath": "Device.WiFi.AccessPoint.1.",
                                "resultParams": {
                                    "Alias": "cpe-1"
                                }
                            }
                        ]
                    }
                ]
            }
        }
    }
}

The response looks good except for the request path "Device.WiFi.AccessPoint.*.Security.ModeEnabled" . I was expecting response is like below but actual was above(highlighted). Which one is as per design/standard ?

                        "resolvedPathResults": [
                            {
                                "resolvedPath": "Device.WiFi.AccessPoint.1.Security.",
                                "resultParams": {
                                    "ModeEnabled": "WPA2-Personal"
                                }
                            }
                        ]

**Comment by holme-r** [comment]
OBUSPA supports both response formats. To obtain the other response format, define GET_RESPONSE_SIMPLE_FORMAT in vendor_defs.h (the line is currently commented out). The upcoming USP 1.2 specification will define which format is preferred.

**Comment by nmurugesan** [comment]
Thank You. it is working with that variable. I will close this ticket
