### ISSUE TITLE
Impossibility to load different client certificates for multiple Client-Broker connections 

### ISSUE THREAD

**Issue by antonioboian** [BroadbandForum/obuspa#28]
Good Afternoon everyone,
I was working on the definition of the load_agent_cert_cb call back with the aim to load a different client certificate based on which is the Client is calling the DEVICE_SECURITY_LoadTrustStore function. However, at this stage for my understanding, it is not possible to retrieve the hostname without changing the source code of the agent, given the fact that only the SSL_CTX is passed.

**Comment by holme-r** [comment]
I'm sorry, but I am a little confused. You don't need to know the server's hostname when loading a client cert. A client cert is the certificate of the USP Agent.
