### ISSUE TITLE
The Agent could not perform re-connection when connecting to a MQTT broker through TLS

### ISSUE THREAD

**Issue by antonioboian** [BroadbandForum/obuspa#29]
Hello everyone
I would like to report the behaviour of the agent when it tries to reconnect to an MQTT broker with TLS after that the first connection fails.
The error generated is the following DEVICE_SECURITY_LoadTrustStore: X509_STORE_add_cert() failed
So in a nutshell, if the broker is up when the Agent startup the Agent will be able to perform the connection with it, if instead, the broker is not up at the Agent startup the Agent will not be able to perform the reconnection process since the DEVICE_SECURITY_LoadTrustStore function fails.
The problem is related to the fact that when performing the reconnection it is passed to the function the same SSL_CTX object, which already contains the Trust store certificates loaded earlier and therefore the function X509_STORE_add_cert() fails. For instance by commenting the first return in DEVICE_SECURITY_LoadTrustStore function everything works

**Comment by holme-r** [comment]
Thanks, also which version of libmosquitto do you see the issue with ?

**Comment by holme-r** [comment]
Closing, as fixed in release 5.0.0.
