### ISSUE TITLE
Testing on USP agent

### ISSUE THREAD

**Issue by kanghuanyao** [BroadbandForum/obuspa#3]
Good day,
I'm testing with the obuspa, however, the "ubuspa in cli mode" uses unix socket to communication with the "ubuspa in daemon mode". Is there a suggested STOMP server and USP controller to test the protocol stack of USP? It will be a great help! Thanks.

**Comment by holme-r** [comment]
We are working on a USP controller that could be used for testing purposes. Please keep monitoring the project for this.

**Comment by michaeljohnsondai** [comment]
> We are working on a USP controller that could be used for testing purposes. Please keep monitoring the project for this.

How's that coming along? Any progress?

**Comment by worldofprasanna** [comment]
@holme-r  Thanks for the USP Agent. We are also eagerly waiting for the USP Controller, so that we can test the full setup. Is there any timeline on when USP Controller would be ready?

**Comment by johnblackford** [comment]
@worldofprasanna it should be released in the February 2020 timeframe.

**Comment by michaeljohnsondai** [comment]
> @worldofprasanna it should be released in the February 2020 timeframe.

@johnblackford Looking forward to taking a look at this. Any updates on a Feb release?

**Comment by michaeljohnsondai** [comment]
> @worldofprasanna it should be released in the February 2020 timeframe.

@johnblackford Not sure if you got my previous reply - Is this still something that's coming out in Feb?

**Comment by johnblackford** [comment]
Sorry I missed your last question @michaeljohnsondai .  We are still tracking to an end of February date.  Please stay tuned.

**Comment by michaeljohnsondai** [comment]
> Sorry I missed your last question @michaeljohnsondai . We are still tracking to an end of February date. Please stay tuned.

@johnblackford no problem at all. Looking forward to seeing this but haven't seen any announcements or other information about it. Where should I keep a look out?

**Comment by johnblackford** [comment]
@michaeljohnsondai, the test controller is now available here: https://github.com/BroadbandForum/obuspa-test-controller 

I'll close this ticket out now.

Thank you.
