### ISSUE TITLE
PublishQos not getting updated in MQTT Publish Message

### ISSUE THREAD

**Issue by arunsivasankar** [BroadbandForum/obuspa#30]
Set PublishQos to 2 using 
obuspa -c set "Device.LocalAgent.MTP.1.MQTT.PublishQoS" 2

Verify the next Publish message is sending MQTT packet with qos 2.
But MQTT Publish message is always having QoS as 0.

Obuspa version used 4.1.0
 
![MQTTPublishQos](https://user-images.githubusercontent.com/1259602/137477374-8ac69397-bf6f-48c9-9e75-fc0c06456701.JPG)
![image](https://user-images.githubusercontent.com/1259602/137478021-7e7a0d58-471e-4b21-b9ca-f2a8714eff3d.png)

**Comment by holme-r** [comment]
Closing as fixed in commit [2022-10-04: Bug fixes]
