### ISSUE TITLE
LocalAgent.MTP Enable/disable is not working as expected

### ISSUE THREAD

**Issue by arunsivasankar** [BroadbandForum/obuspa#33]
when Device.LocalAgent.MTP.1.Enable is set to False, below is the expectation as per 

https://usp-data-models.broadband-forum.org/tr-181-2-14-1-usp.html#D.Device:2.Device.LocalAgent.MTP.{i}.

_Enable/Disable this MTP instance.
If this MTP instance is to be disabled and currently used for communication with the requesting controller, the agent has to send the request response first, before disabling it._

Currently, when MQTT is used as MTP, obuspa disconnects and does not sent the SET_RESP as prescribed by the specification

Obuspa version used 4.1.0

**Comment by holme-r** [comment]
Agreed, OBUSPA should be sending the response before disconnecting. We will fix this.

**Comment by arunsivasankar** [comment]
Thank you holme-r for the update
we are observing two different scenarios here
1. when Device.LocalAgent.Controller.1.MTP.Enable is set to false, obuspa disconnects without sending the response
2. whereas when Device.LocalAgent.MTP.1.Enable is disabled, response is sent , but connection still exists and not teared down.

Expectation as per Spec 
"If this MTP instance is to be disabled and currently used for communication with the requesting controller, the agent has to send the request response first, before disabling it."

**Comment by holme-r** [comment]
Closing as fixed in latest commit.
