### ISSUE TITLE
LocalAgent Subscription ReferenceList is editable 

### ISSUE THREAD

**Issue by arunsivasankar** [BroadbandForum/obuspa#34]
As per spec : Once the value of the Device.LocalAgent.Subscription.{i}.ReferenceList is written, the value cannot be changed as the Subscription instance is considered to be immutable. If the value of a non-empty ReferenceList parameter needs to change, the Subscription instance MUST be deleted and a new Subscription instance created.

But obuspa 4.1.0 allows ReferenceList value to be updated without the need to delete the subscription

**Comment by holme-r** [comment]
Closing as fixed in release 8.0.0
