### ISSUE TITLE
Missing const usage to arguments with USP_LOG_xxxxx calls

### ISSUE THREAD

**Issue by anderewrey** [BroadbandForum/obuspa#35]
See https://issues.broadband-forum.org/browse/OBUSPA-182

In src/core/usp_log[.h|.c] file, the USP_LOG_xxxx functions use the regular "char *" pointer for the string buffer, while it could be improved by using "const char *" pointer instead.

Since the USP_LOG_xxxx functions are not intended to edit the content of the string buffers, changing the "char *" for "const char *" would be the right way to avoid the situation and also to protect the source string buffer.

In USP_LOG_ErrorSSL declaration, the func_name parameter is already using the const, but not the others.

**Comment by holme-r** [comment]
Closing, as changes available in repo.
