### ISSUE TITLE
MQTT KeepAlive 0 Not working as expected

### ISSUE THREAD

**Issue by arunsivasankar** [BroadbandForum/obuspa#36]
Obuspa version used 4.1.0
MTP used : MQTT

Steps 
When Device.MQTT.Client.1.KeepAliveTime is to zero, obuspa disconnects the existing connection and never connects back 

Expected : Agent should keep the MQTT connection intact and just not send the keepalive packets when the value 0 is applied. As this value is updated to broker in connect message, server will not disconnect if no keepalive from agent.

As per spec :
A value of zero (0) means no keep alive packets are sent and the MQTT client is not disconnected by the server.

obupsa agent logs <snip>
SendingConnect
[err] <11>1 2021-10-01T17:07:10.141940+00:00 AONT syslog - - - Failed to connect v5 with Invalid function arguments provided. (3)
[err] <11>1 2021-10-01T17:07:10.142129+00:00 AONT syslog - - - HandleMqttError (MoveState_Private): SendingConnect --> [[ Failed to connect to client ]] --> Error/Retring
[err] <11>1 2021-10-01T17:07:10.142252+00:00 AONT syslog - - - HandleMqttError: Got error: 1, reason: Failed to connect to client, retry_count: 
[MQTTKeepAliveZeroLogs.txt](https://github.com/BroadbandForum/obuspa/files/7553764/MQTTKeepAliveZeroLogs.txt)
9

**Comment by holme-r** [comment]
Closing as issue has been addressed in 24th January 2022 commit.
Note that libmosquitto does not support turning keep alive off entirely. The lowest frequency keep alive achieved is 18 hours.
