### ISSUE TITLE
Build Failure for OBUSPA

### ISSUE THREAD

**Issue by ozsoycagri** [BroadbandForum/obuspa#39]
In order to install OB-USP-AGENT, it is required to execute according to QUICK_START_GUIDE.md file step 3:

$ autoreconf --force --install

The command fails with the following output:

autoreconf: 'configure.ac' or 'configure.in' is required

Quick start guide should be updated with correct installation orders.

**Comment by holme-r** [comment]
Try executing 'autoreconf --force --install' from within the directory that you cloned from github. That directory contains 'configure.ac'

**Comment by ozsoycagri** [comment]
Definitely, the document should be updated to include the following command for git clone step:

git clone https://github.com/BroadbandForum/obuspa.git

**Comment by holme-r** [comment]
Closing as quick start guide updated in latest commit.

**Comment by ozsoycagri** [comment]
Thanks for the quick update.
