### ISSUE TITLE
Does obuspa listen for connections or does it expect to initiate with the controller?

### ISSUE THREAD

**Issue by itbarr** [BroadbandForum/obuspa#4]
Hi there,

Firstly thanks very much for this project! It's great to see something concrete for trying out USP.

This question relates to the v2.0.0 release.

What patterns does obuspa support for establishing the connection between the agent and a controller? Does it listen for connections or does it expect to initiate the connection with the controller? [If initiating does it just support 1 connection at the moment?]

I see in the data model there are some relevant fields with their defaults:

    Device.LocalAgent.Controller.1.EndpointID => self::usp-controller.com
    Device.STOMP.Connection.1.Host => usp-controller.com
    Device.STOMP.Connection.1.Port => 61613
    Device.STOMP.Connection.1.Username => username
    Device.STOMP.Connection.1.Password => password

I assume these are for the agent to use to call a remote endpoint to try and establish the connection?

I'm interested in exploring a use-case where we have a lightweight controller running on something like a smart phone app on the device LAN. This suggests that the connection would need to be initiated by the app and that the agent would need to be listening on a LAN IP.

Is that sort of model supported by this release? I'm thinking of STOMP at this stage until Web Sockets or MQTT are supported.

Regards,
Ivan

**Comment by holme-r** [comment]
With STOMP MTP, obuspa initiates connection to a STOMP message broker. The USP controller will also connect to the STOMP message broker. It is possible to initiate connections to multiple STOMP message brokers by configuring instances of the "Device.STOMP." object and linking this to a controller by configuring the "Device.LocalAgent.Controller.{i}.MTP.{i}.STOMP." object.

CoAP MTP is different. It is peer-to-peer rather than brokered. With CoAP, obuspa listens for connections.

Both STOMP and CoAP could support your use case. CoAP requires less infrastructure and is more suited as long as the controller can discover the IP address of the agent (for example using MDNS).

**Comment by itbarr** [comment]
Thanks for the speedy reply!

For my example of a LAN side controller on a smart phone there is a scenario where the WAN connection is down on the CPE. This means the app couldn't talk to the controller if the STOMP message broker is in the cloud (the app might get to the broker via it's own mobile connection but the device wouldn't be able to get to the broker). For this scenario does that suggest you'd need a broker on the CPE? (purely to support LAN connections from controllers).

**Comment by holme-r** [comment]
CoAP is more suited for your use case. However if you really wanted to use STOMP, the STOMP message broker could be resident on a router or some other device on the LAN (even potentially built in to the controller or resident on the CPE).

**Comment by itbarr** [comment]
Thanks!

Let's say we want to build a user facing management app. It would be nice to do this in a way which is re-usable across a number of exposures e.g. a smart phone app, maybe a set-top box app and a web app i.e. just simply running in a web browser [as you could argue that logically the device management GUI is actually a just another simple "controller" in function]. I could be wrong but I'm not sure that CoAP is doable from something running in a browser.

**Comment by holme-r** [comment]
For CoAP library implementations, please see https://coap.technology/impls.html. There is a Javascript library that runs on node.js which might be suitable for portable smart phone apps, though not pure browser web apps.

**Comment by johnblackford** [comment]
Looks like this has reached conclusion, closing.
