### ISSUE TITLE
See the specification in TP-143 test cases in BBF – 6 STOMP Test Cases  section: stomp-destination---terminates-unconfigured-session

### ISSUE THREAD

**Issue by dandan626** [BroadbandForum/obuspa#40]
In the specification in TP-143 test cases in [BBF – 6 STOMP Test Cases]
[https://usp-test.broadband-forum.org/07-index-stomp-test-cases.html#sec:stomp-destination---terminates-unconfigured-session](url)

The test case expect the USP agent to send an DISCONNECT to controller when its Device.LocalAgent.MTP.{i}.STOMP.Destination is set to empty.
But obuspa does not send the DISCONNECT to controller.

obuspa version: 4.0

**Comment by holme-r** [comment]
Thank you for reporting this issue. I can reproduce the issue, and we will fix it in a later release.

**Comment by holme-r** [comment]
Closing as this issue has been addressed in the latest commit.
