### ISSUE TITLE
OBUSP Agent response for GET : resolved path & result_params

### ISSUE THREAD

**Issue by navshekhawat** [BroadbandForum/obuspa#41]
Hi Team,

We are using obusp agent to connect to stomp server and in turn connects to controller.
The agent is able to connect to stomp server and both agent and stomp server has connectivity.

When we issue onboard request using operate:
command:
obuspa -f agent.db -c operate "Device.LocalAgent.Controller.1.SendOnBoardRequest()"

header {
  msg_id: "OnBoardRequest-2022-03-04T12:02:21Z-1"
  msg_type: NOTIFY
}
body {
  request {
    notify {
      subscription_id: ""
      send_resp: false
      on_board_req {
        oui: "00BBF"
        product_class: "PC"
        serial_number: "E65F12345313"
        agent_supported_protocol_versions: "1.0,1.1"
      }
    }
  }
}

Based on above response the agent (obusp agent version is shown as  agent_supported_protocol_versions: "1.0,1.1")

The controller is trying to get the object from agent using GET:
header {
  msg_id: "5267995"
  msg_type: GET
}
body {
  request {
    get {
      param_paths: "Device.LocalAgent.Controller.[EndpointID=="self:ctrlr:controller"].MTP."
      max_depth: 0
    }
  }
}

**The agent is returning response as:**

header {
  msg_id: "5267995"
  msg_type: GET_RESP
}
body {
  response {
    get_resp {
      req_path_results {
        requested_path: "Device.LocalAgent.Controller.[EndpointID=="self:ctrlr:controller"].MTP."
        err_code: 0
        err_msg: ""
        resolved_path_results {
          resolved_path: "Device.LocalAgent.Controller.1.MTP."
          result_params {
            key: "1.Alias"
            value: "cpe-1"
          }
          result_params {
            key: "1.Enable"
            value: "true"
          }
          result_params {
            key: "1.Protocol"
            value: "STOMP"
          }
        }
      }
    }
  }
}

In the above response:
resolved_path: "Device.LocalAgent.Controller.1.MTP." and result_params with index.key 1.Alias" are returned.

Is this the correct behaviour of obusp agent sending data in above format.

But we are facing issue at our side as we are expecting resolved_path to be "Device.LocalAgent.Controller.1.MTP.1."

and result params without index as shown below:

result_params {
    key: "Enable"
    value: "true"
  }
  result_params {
    key: "Protocol"
    value: "STOMP"
  }

Could it be possible for obusp agent to send the data in above format.
We are referring head: **7.5.2.1 GetInstances Examples** from  https://usp.technology/specification/07-index-messages.html#sec:reading-an-agents-state-and-capabilities

It would be great help to get answers on the above behaviour.

Thank you.

**Comment by navshekhawat** [comment]
Thank you Richard will un comment the code mentioned and test.

**Comment by holme-r** [comment]
Closing as the latest commit has GET_RESPONSE_SIMPLE_FORMAT defined by default in vendor_defs.h.
