### ISSUE TITLE
MaxSubscriptionChangeAdoptionTime support

### ISSUE THREAD

**Issue by italktothewind** [BroadbandForum/obuspa#44]
Hi,

I'm having a 30 secs delay between changing the value of a parameter which I'm subscribed to and receiving the value change notification. I tried to change the data model property Device.LocalAgent.MaxSubscriptionChangeAdoptionTime but it seems that it is not supported.

Is there any way to reduce that amount of time?

Thanks!

**Comment by holme-r** [comment]
You can modify VALUE_CHANGE_POLL_PERIOD in vendor_defs.h. I would caution against reducing that time too much, as it is the polling interval for all value change subscriptions. If you have a very short polling interval, and a large number of value change parameters subscribed, then your device will spend a lot of CPU time polling for value change.

**Comment by italktothewind** [comment]
I will try that, thanks!

**Comment by italktothewind** [comment]
Changing the VALUE_CHANGE_POLL_PERIOD property worked for me. Thanks.
