### ISSUE TITLE
Firmware file for obuspa

### ISSUE THREAD

**Issue by italktothewind** [BroadbandForum/obuspa#45]
Hi!

I'm trying to write a test where my controller performs the Dowload() command on this agent.

That command requires an URL where the agent can download the new firmware.

Which firmware file can I use for this purpose?

Thanks!

**Comment by holme-r** [comment]
The firmware file is a a file that you need to create for your device. There isn't a standard format for this file (device/platform specific), nor does OBUSPA provide any code to deal with this file. The core OBUSPA data model does not include the Download() command - you will need to add one by calling USP_REGISTER_AsyncOperation(). The implementation of that command (and possibly the Activate command too) will deal with the file format of your firmware image file and apply it.

**Comment by italktothewind** [comment]
Thanks for the information

**Comment by KuoEuran** [comment]
Hi @holme-r ,
     I have some questions about implement the firmware download function.
1. As rdkb has defined datamodel "Device.DeviceInfo.FirmwareImage.{i}.Download()", should I call this datamodel or I can define my own datamodel to call?
2. You have mentioned that it uses USP_REGISTER_AsyncOperation(), but I only found one place (usp_register.c) has the code. Do I also call my download function in this .c file? or init( ) in vendor.c?
