### ISSUE TITLE
Obuspa support for protocol features

### ISSUE THREAD

**Issue by italktothewind** [BroadbandForum/obuspa#49]
Hi! I would like to know if obuspa is currently supporting the following features present in the TR3969 spec (https://www.broadband-forum.org/download/TR-369.pdf):

1) Bulk Data Collection (page 156). These are periodic reports with several parameters at once. They can be posted in an HTTP endpoint or sent to a MQTT topic.

2) Exchange of USP Records within an E2E Session Context (page 70). All the messages I receive from OB-USP-A are without a session context. Does it supports sessions? How can I force it?

3) Authentication and Authorization (page 138). What security mechanisms does OB-USP-A support?

Thanks!!

**Comment by holme-r** [comment]
1. Bulk Data Collection is supported over HTTP or USP notifications (Push! events). It is not yet supported over MQTT.
2. Basic session context (segmentation and reassembly aspects) can be enabled by uncommenting the E2ESESSION_EXPERIMENTAL_USP_V_1_2 define in vendor_defs.h.
3. Two way certificate based authentication is supported.

**Comment by italktothewind** [comment]
Thanks for the information
