### ISSUE TITLE
obuspa set is getting queued & delayed  

### ISSUE THREAD

**Issue by mrkarthik1132** [BroadbandForum/obuspa#51]
Triggered Factory reset, obuspa set is getting queued & delayed  after updating WAN configs.
Suspecting "MQTT_ActivateScheduledActions" API could not able to acquire mutex lock over "mqtt_access_mutex" refer snippet #2.
Refer snippet #3 for timestamp logs.  
---------------------------------------------------------------------------------
[root@AONT: writeuser]# obuspa -c set Device.LocalAgent.Controller.1.EndpointID "self:hdmept:controller"  -> **This set was queued & delayed refer Snippet #1**  
Failed to connect v5 with Connection timed out (14)
Device.LocalAgent.Controller.1.EndpointID => self:hdmept:controller
[root@AONT: writeuser]#

---------------------------------------------------------------------------------
**Snippet #1**  
[root@AONT: writeuser]# ps | grep usp
5247 appServi 57732 S    /sbin/obuspa -v 1 -r /etc/uspfactory_reset.conf -l syslog
8027 root     15944 S    obuspa -c set Device.LocalAgent.Controller.1.EndpointID self:hdmept:controller
8180 root      3152 S    grep usp
[root@AONT: writeuser]#
---------------------------------------------------------------------------------
Snippet #2

void MQTT_ActivateScheduledActions(void)
{
    int i;
    mqtt_client_t* client;
    OS_UTILS_LockMutex(&mqtt_access_mutex);
    syslog(LOG_ERR, "\n %s/%d",__FUNCTION__,__LINE__);
    if (is_mqtt_mtp_thread_exited)
    {
        OS_UTILS_UnlockMutex(&mqtt_access_mutex);
        return;
    }
---------------------------------------------------------------------------------
Snippet #3

[err] <131>1 1970-01-01T00:16:44.484111+00:00 AONT syslog - - -  obuspa set controllerEndpoint =self:hdmept:controller
[err] <131>1 1970-01-01T00:16:44.484250+00:00 AONT syslog - - -  obuspa set mtp_protocol =MQTT
[err] <131>1 1970-01-01T00:16:44.484386+00:00 AONT syslog - - -  obuspa set mqtt_transportprotocol =TCP/IP
[err] <131>1 1970-01-01T00:16:44.484620+00:00 AONT syslog - - -  obuspa set mqtt_brokeraddress =181.117.5.1
[err] <131>1 1970-01-01T00:16:44.484981+00:00 AONT syslog - - -  obuspa set mqtt_brokerport =1883
[err] <131>1 1970-01-01T00:16:44.485304+00:00 AONT syslog - - -  obuspa set mqtt_username =5cf9fd7ee990
[err] <131>1 1970-01-01T00:16:44.485589+00:00 AONT syslog - - -  obuspa set mqtt_password =abc
[err] <131>1 1970-01-01T00:16:44.485861+00:00 AONT syslog - - -  obuspa set isPassChanged =1
[err] <131>1 1970-01-01T00:16:44.486142+00:00 AONT syslog - - -  obuspa set data begain
[err] <11>1 1970-01-01T00:16:44.658996+00:00 AONT syslog - - -  #012  ExecuteCli_Set/745
[err] <11>1 1970-01-01T00:16:44.659133+00:00 AONT syslog - - -  #012  ExecuteCli_Set/747
[err] <11>1 1970-01-01T00:16:44.659227+00:00 AONT syslog - - -  #012  ExecuteCli_Set/756
[err] <11>1 1970-01-01T00:16:44.659342+00:00 AONT syslog - - -  #012  ExecuteCli_Set/764
[err] <11>1 1970-01-01T00:16:44.664112+00:00 AONT syslog - - -  #012  ExecuteCli_Set/772
[err] <11>1 1970-01-01T00:16:44.664232+00:00 AONT syslog - - -  #012  ExecuteCli_Set/776
[err] <11>1 1970-01-01T00:16:44.665426+00:00 AONT syslog - - -  #012  ExecuteCli_Set/780
[err] <11>1 1970-01-01T00:16:44.665547+00:00 AONT syslog - - -  #012  ExecuteCli_Set/788
[err] <11>1 1970-01-01T00:16:44.687079+00:00 AONT syslog - - -  #012  ExecuteCli_Set/796
[err] <11>1 1970-01-01T00:16:44.687227+00:00 AONT syslog - - -  #012  MTP_EXEC_ActivateScheduledActions/295
[err] <11>1 1970-01-01T00:16:44.687378+00:00 AONT syslog - - -  #012  MTP_EXEC_ActivateScheduledActions/297
[err] <11>1 1970-01-01T00:16:44.687541+00:00 AONT syslog - - -  #012  MTP_EXEC_ActivateScheduledActions/301
[err] <11>1 1970-01-01T00:16:44.687693+00:00 AONT syslog - - -  #012  MTP_EXEC_ActivateScheduledActions/305
[err] <11>1 1970-01-01T00:16:44.687851+00:00 AONT syslog - - -  #012  MTP_EXEC_ActivateScheduledActions/308
[err] <11>1 1970-01-01T00:16:44.688007+00:00 AONT syslog - - -  #012  MTP_EXEC_ActivateScheduledActions/315
[err] <11>1 1970-01-01T00:16:44.688167+00:00 AONT syslog - - -  #012  MTP_EXEC_ActivateScheduledActions/347
[err] <11>1 1970-01-01T00:16:44.688336+00:00 AONT syslog - - -  #012  MTP_EXEC_ActivateScheduledActions/351

[err] <11>1 1970-01-01T00:17:28.000801+00:00 AONT syslog - - -  #012  MQTT_ActivateScheduledActions/2203
[err] <11>1 1970-01-01T00:17:28.000959+00:00 AONT syslog - - -  #012  MQTT_ActivateScheduledActions/2210
[err] <11>1 1970-01-01T00:17:28.001076+00:00 AONT syslog - - -  #012  MQTT_ActivateScheduledActions/2215
[err] <11>1 1970-01-01T00:17:28.001192+00:00 AONT syslog - - -  #012  MQTT_ActivateScheduledActions/2215
[err] <11>1 1970-01-01T00:17:28.001310+00:00 AONT syslog - - -  #012  MQTT_ActivateScheduledActions/2215
[err] <11>1 1970-01-01T00:17:28.001430+00:00 AONT syslog - - -  #012  MQTT_ActivateScheduledActions/2215
[err] <11>1 1970-01-01T00:17:28.001556+00:00 AONT syslog - - -  #012  MQTT_ActivateScheduledActions/2215
[err] <11>1 1970-01-01T00:17:28.001681+00:00 AONT syslog - - -  #012  MQTT_ActivateScheduledActions/2227
[err] <11>1 1970-01-01T00:17:28.001812+00:00 AONT syslog - - -  #012  MQTT_ActivateScheduledActions/2229
[err] <11>1 1970-01-01T00:17:28.001964+00:00 AONT syslog - - -  #012  ExecuteCli_Set/799
[err] <11>1 1970-01-01T00:17:28.002087+00:00 AONT syslog - - -  #012  ExecuteCli_Set/803
---------------------------------------------------------------------------------

**Comment by holme-r** [comment]
This looks like an issue that was addressed in release 5. The call to mosquitto_connect is blocking whilst it's attempting to connect - which could be for about a minute if the server doesn't respond (which seems to be the case from your log).
The problem was that the mqtt_access_mutex was taken before mosquitto_connect was called, preventing other actions in the data model from occurring. The fix was to release the mutex around the call to mosquitto_connect.
Please recheck with release 5 or later.

**Comment by mrkarthik1132** [comment]
Thanks for your response.
