### ISSUE TITLE
MQTT headers in log

### ISSUE THREAD

**Issue by italktothewind** [BroadbandForum/obuspa#52]
Hi,

Is there any way to log the MQTT message properties present in a received PUBLISH message?

Thanks!

**Comment by italktothewind** [comment]
My question arose when reading this in the documentation: "R-MQTT.27 - USP Endpoints sending a USP Record using MQTT 5.0 MUST have “usp.msg” in the Content Type property" (https://www.broadband-forum.org/download/TR-369.pdf)

Now I'm testing how to send that in MQTT headers.

**Comment by italktothewind** [comment]
FYI these MQTT properties can be logged in Mosquitto: https://stackoverflow.com/questions/72538385/how-to-see-message-mqtt-properties-when-using-mosquitto-sub-command

**Comment by holme-r** [comment]
OBUSPA implements R-MQTT.27, but it does not appear that libmosquitto provides this level of detail to the LogCallback() function in mqtt.c. The mosquitto sub command must have application code that iterates over all of the properties and logs them. OBUSPA does not do this.
For your testing, I'd use the mosquitto sub command or wireshark.
