### ISSUE TITLE
Error when trying to create image obuspa:latest

### ISSUE THREAD

**Issue by AnaCatusanu** [BroadbandForum/obuspa#54]
Hi, I receive this error when trying to build the agent with Docker:
QUICK_GUIDE:Running OBUSPA inside Docker
You can also run OBUSPA within docker. Simply build the docker container, and tag with obuspa:latest.
docker build -t obuspa:latest .

I was using the Dockerfile provided (FROM ubuntu:latest ; tested also with FROM ubuntu:impish) on a Windows10:

#7 45.65 Setting up python3-software-properties (0.99.24) ...
#7 45.83 Setting up software-properties-common (0.99.24) ...
#7 46.04 Processing triggers for libc-bin (2.35-0ubuntu3) ...
#7 46.15 Processing triggers for dbus (1.12.20-2ubuntu4) ...
#7 47.26 Traceback (most recent call last):
#7 47.26   File "/usr/bin/add-apt-repository", line 364, in <module>
#7 47.26     sys.exit(0 if addaptrepo.main() else 1)
#7 47.26   File "/usr/bin/add-apt-repository", line 347, in main
#7 47.26     shortcut = handler(source, **shortcut_params)
#7 47.26   File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
#7 47.26     return handler(shortcut, **kwargs)
#7 47.26   File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 82, in __init__
#7 47.26     if self.lpppa.publish_debug_symbols:
#7 47.26   File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 120, in lpppa
#7 47.26     self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
#7 47.26   File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 107, in lpteam
#7 47.26     self._lpteam = self.lp.people(self.teamname)
#7 47.26   File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 98, in lp
#7 47.26     self._lp = login_func("%s.%s" % (self.__module__, self.__class__.__name__),
#7 47.26   File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 494, in login_anonymously
#7 47.26     return cls(
#7 47.26   File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 230, in __init__
#7 47.26     super(Launchpad, self).__init__(
#7 47.26   File "/usr/lib/python3/dist-packages/lazr/restfulclient/resource.py", line 472, in __init__
#7 47.26     self._wadl = self._browser.get_wadl_application(self._root_uri)
#7 47.26   File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 447, in get_wadl_application
#7 47.26     response, content = self._request(url, media_type=wadl_type)
#7 47.26   File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 389, in _request
#7 47.26     response, content = self._request_and_retry(
#7 47.26   File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 359, in _request_and_retry
#7 47.26     response, content = self._connection.request(
#7 47.26   File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1701, in request
#7 47.26     (response, content) = self._request(
#7 47.26   File "/usr/lib/python3/dist-packages/launchpadlib/launchpad.py", line 144, in _request
#7 47.26     response, content = super(LaunchpadOAuthAwareHttp, self)._request(
#7 47.26   File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 184, in _request
#7 47.26     return super(RestfulHttp, self)._request(
#7 47.26   File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1421, in _request
#7 47.26     (response, content) = self._conn_request(conn, request_uri, method, body, headers)
#7 47.26   File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1343, in _conn_request
#7 47.26     conn.connect()
#7 47.26   File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1135, in connect
#7 47.26     self.sock = self._context.wrap_socket(sock, server_hostname=self.host)
#7 47.26   File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
#7 47.26     return self.sslsocket_class._create(
#7 47.26   File "/usr/lib/python3.10/ssl.py", line 1071, in _create
#7 47.26     self.do_handshake()
#7 47.26   File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
#7 47.26     self._sslobj.do_handshake()
#7 47.26 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
#7 ERROR: executor failed running [/bin/sh -c apt-get update &&     apt-get install -y software-properties-common &&    add-apt-repository ppa:mosquitto-dev/mosquitto-ppa]: exit code: 1
------
 > [4/7] RUN apt-get update &&     apt-get install -y software-properties-common &&     add-apt-repository ppa:mosquitto-dev/mosquitto-ppa:
------
executor failed running [/bin/sh -c apt-get update &&     apt-get install -y software-properties-common &&      add-apt-repository ppa:mosquitto-dev/mosquitto-ppa]: exit code: 1

Can you help me with this? Regards!

**Comment by holme-r** [comment]
As a workaround, have you tried modifying the Dockerfile:
    add-apt-repository --allow-unauthenticated ppa:mosquitto-dev/mosquitto-ppa

**Comment by AnaCatusanu** [comment]
Hi, I've tried to modify the Dockerfile with various "internet solutions/suggestions", but nothing worked. Also, it seems that --alow-unauthenticated is not a valid argument for apt-add-repository. Thanks for the response.

**Comment by rennyahernandez** [comment]
I solved this using `ubuntu:focal`  instead of `ubuntu:latest`.  The solution can be found in #55
