### ISSUE TITLE
Certificate commands

### ISSUE THREAD

**Issue by italktothewind** [BroadbandForum/obuspa#56]
Hi,

I would like if obuspa is supporting AddCertificate() and AddMyCertificate() commands. If not, if there is another way to load certificates into the agent.

Thanks in advance!

**Comment by holme-r** [comment]
OBUSPA doesn't currently support AddCertificate() or AddMyCertificate() and there is no support for dynamically adding/deleting trust store certificates. You can use the get_agent_cert_cb vendor hook or the -t option to specify the trust store certs when OBUSPA starts.  See the QUICK_START_GUIDE for more info.

**Comment by italktothewind** [comment]
Thanks for the information
