### ISSUE TITLE
Firmware Download Fucntionality

### ISSUE THREAD

**Issue by shanthakumarks** [BroadbandForum/obuspa#6]
Do we have the firmware download functionality supported by ob-uspagent in the current ob-usp-agent 2.1.1 release ? We are planning to test the firmware download functionality of ob-uspagent against CDRouter. Teh firmware download functionality doesn't seem to be working so far. 

If not, is it something on the roadmap to be released in furture releases? 

I could see that the file src/core/device_firmware.c has a placeholder for contributors to implement the Device.LocalAgent.FirmwareImage. Object. I also see that the required data types for Download() operation is defined in the file src/include/usp_api.h. Does it mean that firmware upgrade functionality is already under development ? 

Can you also please throw some light on the roadmap of the upcoming functionalites in near furture ? Also what is expected from the contributors and integrators to focus on ?

**Comment by holme-r** [comment]
There are no current plans to provide a firmware upgrade mechanism in OBUSPA, as firmware upgrade is very device specific.
So the project might remove the unused code until such a time that the project implements some kind of example firmware upgrade solution.
The unused code could be extended to form a device specific upgrade mechanism.

**Comment by johnblackford** [comment]
Closing based on the comment from @holme-r
