### ISSUE TITLE
Vendor Reboot and Reset command

### ISSUE THREAD

**Issue by epicmanmoo** [BroadbandForum/obuspa#61]
Hello,

We are trying to use our own Reboot and Factory Reset commands with an API. However, it looks like we need to modify the core code in obuspa. Is there any way to implement our own logic for these commands without touching the core code?

Thanks.

**Comment by holme-r** [comment]
You can register callbacks to implement the Reboot and Factory Reset commands. See the QUICK_START_GUIDE section "Overriding the Core Implementation" for details. Not using these callbacks would require touching the core code and you would need to be careful that you shutdown OBUSPA gracefully before rebooting. So using the callbacks is the recommended way.
