### ISSUE TITLE
Wrong boot message when using the Factory Reset command

### ISSUE THREAD

**Issue by epicmanmoo** [BroadbandForum/obuspa#62]
Hello,

We have written vendor code to use our own callback functions to execute Reboot and Factory Reset commands on the device. Both commands are working fine and as expected, but one issue which we noticed is that the "Cause" message on "Boot!" does not indicate "RemoteFactoryReset" when running the "Factory Reset" command from our controller. Instead, using Factory Reset ends up saying "LocalReboot". We looked through the code a bit and realized this happens because "usp.db" is deleted, which then causes the "Cause" message on "Boot!" to rely on the default value of "LocalReboot". This seems like a bug since it should be showing "RemoteFactoryReset", just as it shows "RemoteReboot" when the reboot command is used. We were thinking of generating a temp/hidden file that would be created when the "Factory Reset" command is used and then looked for at "Boot!" to check if the file exists. If it did, the "Cause" would be a "RemoteFactoryReset" else "LocalReboot". Nonetheless, we do not want to implement this idea because the logic is in the core code and we cannot modify the static "local_reboot_cause_str" defined in "device_local_agent.c"... 
Hope you can provide some insight into this!

Thank you.

**Comment by holme-r** [comment]
Try setting Internal.Reboot.Cause to "RemoteFactoryReset" in your OBUSPA factory reset file (-r option) or in the script you use to create a factory reset database (using dbset commands). If you don't do this, then you will get the default value of "LocalReboot" - which isn't what you want.

That said, you normally need to differentiate between "RemoteFactoryReset" and "LocalFactoryReset", and you would need another flag (eg using a file that persists a factory reset partition wipe - as you suggested) to achieve this.
