### ISSUE TITLE
OB-USP-A TLS features

### ISSUE THREAD

**Issue by italktothewind** [BroadbandForum/obuspa#63]
If I understood well the USP documentation (please correct me if I am wrong), there are two ways of making secure the connection between the controller and the agent:

1) Establish a TLS connection between the controller and the broker and a TLS connection between the broker and the agent:

`CONTROLLER <--TLS over MQTT messages--> BROKER <--TLS over MQTT messages--> AGENT `

2) Establish a TLS connection between the controller and the agent, peer to peer, inside a session context:

`CONTROLLER <--TLS over USP messages--> AGENT `

I asked in other issue if OB-USP-A supported some of these security mechanisms and you told me: “two way certificate based authentication is supported”.

I would like to know if you are referring to 1) or 2) or both of them.

Thanks in advance!

**Comment by holme-r** [comment]
I was just referring to 1. Session Context support is currently limited to only basic segmentation and reassembly aspects. It does not include TLS aspects.

**Comment by italktothewind** [comment]
Thanks for the information.
