### ISSUE TITLE
Problem when setting PeriodicNotifInterval to 0 in Obuspa 5.0.0 and 6.0.0

### ISSUE THREAD

**Issue by stevenvtech** [BroadbandForum/obuspa#64]
After PeriodicNotifInterval is set to 0 and send it to the OBUSPA agent from the controller, the OBUSPA agent will crash and cannot be recovered by simple reboot.
Even the latest OBUSPA version 6.0.0 has such an issue.

**Comment by holme-r** [comment]
Thank you for finding this bug. The fix for this issue is quite simple - there should be a validation callback for the parameter.
We will look to address this shortly.

**Comment by holme-r** [comment]
Closing as fixed in commit [2022-10-04: Bug fixes]
