### ISSUE TITLE
Force OB-USP-A to require secure connection

### ISSUE THREAD

**Issue by italktothewind** [BroadbandForum/obuspa#65]
Hi!

In this [issue](https://github.com/BroadbandForum/obuspa/issues/63) you told me that OB-USP-A supports TLS at broker level. I would like to know how can I configure OB-USP-A to fail if there isn't a secure connection (figures 16, 17 and 18 in the [documentation](https://usp.technology/specification/08-index-auth.html#sec:self-signed-certificates)).

I didn't find any related option :(

Thanks in advance

**Comment by holme-r** [comment]
OBUSPA doesn't support E2E encryption. Therefore if we forced OBUSPA to fail if there isn't a secure connection, then that would mean that we shouldn't allow non-TLS MTP connections. But non-TLS MTP connections are very useful in development. And in deployment, you would always use a TLS MTP connection. Therefore there doesn't seem a very strong need to fail messages in the case of non-TLS - the only time non-TLS is used is in development where you don't want messages to be dropped in that case.
