### ISSUE TITLE
Failed to set properties in factory_reset.txt file

### ISSUE THREAD

**Issue by italktothewind** [BroadbandForum/obuspa#66]
Hi!

I set the serial number in factory_reset.txt in the following way:

Device.DeviceInfo.SerialNumber "serialNumber"

And it worked. But when I want to set more properties:

Device.DeviceInfo.ManufacturerOUI "oui"
Device.DeviceInfo.ProductClass "productClass"
Device.DeviceInfo.SerialNumber "serialNumber"

Only the first one (ManufacturerOUI) is being set.

Any advice?

Thanks in advance.

**Comment by holme-r** [comment]
As a log would show, some parameters cannot be set in the factory reset file. 
OBUSPA stops reading the file at the first failure (ProductClass).
* ProductClass is set by the VENDOR_PRODUCT_CLASS define in vendor_defs.h.
* SerialNumber is normally set by the get_agent_serial_number_cb vendor hook, but it can also fall back to MAC Address, or be overridden by the factory reset file.
