### ISSUE TITLE
Cmake/ninja support

### ISSUE THREAD

**Issue by ahmedarif193** [BroadbandForum/obuspa#69]
for a better easy to use project file and less build time I'm planning to add the cmake/ninja support, CmakeLists.txt will contains the same default options as the previous build-system, a fluent transition between the two build systems requires to keep both of them in the same project while making the old one deprecated, then delete it in the next release.

any recommendations ?

**Comment by holme-r** [comment]
Thank you for offering to add and be the maintainer for cmake/ninja support. This would need to be in addition to the existing autotools based build system. As many projects are already using the autotools based one, we cannot deprecate it, or remove it.

**Comment by holme-r** [comment]
Closing, as we've just added CMake support in v7.0.1.
