### ISSUE TITLE
certificate authenticating

### ISSUE THREAD

**Issue by Scott-Zou-Developer** [BroadbandForum/obuspa#7]
Good day,
I'm testing with the obuspa. I implemented the MQTT protocol with reference to the Stomp protocol.
However I get an error “LoadClientCert: Not using a device certificate for connections”. It will be a great help! Thanks.

**Comment by johnblackford** [comment]
@Scott-Zou-Developer, thanks for your interest in the project.  We are currently working on the Release 3, which will include support for MQTT.  Release 3 should be available relatively soon.

I would also encourage you to look at the Contributing.md file and consider joining the project.

As to your LoadClientCert question, @holme-r should be able to address that.

**Comment by holme-r** [comment]
@Scott-Zou-Developer 
Don't worry about that log message, it's informational only (see the code in LoadClientCert() ), and is to be expected if you aren't using a client cert for the device.

**Comment by Scott-Zou-Developer** [comment]
Thanks for the speedy reply! I will continue this project.
