### ISSUE TITLE
Dynamic Roles/Permissions

### ISSUE THREAD

**Issue by Jiaoding** [BroadbandForum/obuspa#70]
I want to add Roles/Permissions dynamically and could you tell me where to register addrole api?

**Comment by holme-r** [comment]
I'm sorry but OBUSPA only currently (v6.x) supports roles/permissions registered during start up. Roles must be enumerated in ctrust_role_t in vendor_defs.h. The register_controller_trust_cb vendor hook registers roles by calling USP_DM_RegisterRoleName() and permissions by calling USP_DM_AddControllerTrustPermission(). The data model path passed to USP_DM_AddControllerTrustPermission() must contain only wildcards or partial path - instance numbers and search expressions are not supported. See RegisterDefaultControllerTrust() for an example of the register_controller_trust_cb vendor hook.
