### ISSUE TITLE
Periodic! Event for basic statistics collection periodically  

### ISSUE THREAD

**Issue by shanthakumarks** [BroadbandForum/obuspa#71]
Hi,

Can the"Device.LocalAgent.Periodic!" event still be used for sending parameter and value pair along with the event to the USP controller for collecting some basic statistics like how Periodic Inform is used in TR069 ? If yes, is there any mechanism available today to add list of parameters while subscribing for the Periodic! event from the USP Controller ? or If Periodic! event is not designed for statistics collection purpose, is Bulkdata collection mechanism the only option to collect periodic data collection ?

Provided a sample Periodic Event with empty params. Looking for option to add parameter and value pairs in the "params" block in the event notify message. 
`
{
  "header": {
    "msgId": "Event-2023-02-02T22:08:15Z-24",
    "msgType": "NOTIFY"
  },
  "body": {
    "request": {{
  "
      "notify": {
        "subscriptionId": "periodic-1",
        "sendResp": false,
        "event": {
          "objPath": "Device.LocalAgent.",
          "eventName": "Periodic!",
          "params": {
          }
        }
      }
    }
  }
}`

**Comment by holme-r** [comment]
The controller could get the stats, in response to receiving the Periodic! event.
Alternatively you could use Bulk Data Collection and the Push! event for stats collection.

**Comment by shanthakumarks** [comment]
Do you mean perform GET operation on the required parameters in response to receiving the Periodic! event ?

**Comment by holme-r** [comment]
Yes

**Comment by shanthakumarks** [comment]
Thanks for the clarification.

**Comment by jswalls** [comment]
@shanthakumarks There is also the Periodic Statistics object that lets you get notified periodically with sampled data: https://usp-data-models.broadband-forum.org/tr-181-2-15-1-usp.html#T.D.Device:2.Device.PeriodicStatistics.
