### ISSUE TITLE
Dependent object question 

### ISSUE THREAD

**Issue by dmounday** [BroadbandForum/obuspa#77]
Is the following an error in obuspa, a specification error in TR-181, or my misunderstanding?
A Get Device.LocalAgent.Controller. returns all MTP protocol sub-objects regardless of the value of the .Controller.{i}.MTP.{i}.Protocol parameter. TR-181 describes each protocol sub-object as only present if the object corresponds to the value of the Protocol parameter.
For example the TR-181 of .MTP.{i}.STOMP. description is:
_If the USP Endpoint uses the STOMP Message Transport Protocol (MTP), then this object contains STOMP Client specific configuration parameters related to how this Controller communicates with the STOMP Server.
This object MUST be present if, and only if, [Protocol](https://usp-data-models.broadband-forum.org/tr-181-2-15-1-usp.html#D.Device:2.Device.LocalAgent.Controller.{i}.MTP.{i}.Protocol) is [STOMP](https://usp-data-models.broadband-forum.org/tr-181-2-15-1-usp.html#D.Device:2.Device.LocalAgent.Controller.%7Bi%7D.MTP.%7Bi%7D.Protocol.STOMP)._

The response from obuspa is:
resolved_path_results {
          resolved_path: "Device.LocalAgent.Controller.1.MTP.1."
          result_params {
            key: "Alias"
            value: "cpe-1"
          }
          result_params {
            key: "Enable"
            value: "true"
          }
          result_params {
            key: "Protocol"
            value: "WebSocket"
          }
        }
        resolved_path_results {
          resolved_path: "Device.LocalAgent.Controller.1.MTP.1.STOMP."
          result_params {
            key: "Reference"
            value: ""
          }
          result_params {
            key: "Destination"
            value: ""
          }
        }
        resolved_path_results {
          resolved_path: "Device.LocalAgent.Controller.1.MTP.1.CoAP."
          result_params {
            key: "Host"
            value: ""
          }
          result_params {
            key: "Port"
            value: "5683"
          }
          result_params {
            key: "Path"
            value: ""
          }
          result_params {
            key: "EnableEncryption"
            value: "true"
          }
        }
        resolved_path_results {
          resolved_path: "Device.LocalAgent.Controller.1.MTP.1.MQTT."
          result_params {
            key: "Reference"
            value: ""
          }
          result_params {
            key: "Topic"
            value: ""
          }
        }
        resolved_path_results {
          resolved_path: "Device.LocalAgent.Controller.1.MTP.1.WebSocket."
          result_params {
            key: "Host"
            value: "0.0.0.0"
          }
          result_params {
            key: "Port"
            value: "8183"
          }
          result_params {
            key: "Path"
            value: "/gs-server"
          }
          result_params {
            key: "EnableEncryption"
            value: "false"
          }
          result_params {
            key: "KeepAliveInterval"
            value: "30"
          }
          result_params {
            key: "CurrentRetryCount"
            value: "0"
          }
          result_params {
            key: "SessionRetryMinimumWaitInterval"
            value: "5"
          }
          result_params {
            key: "SessionRetryIntervalMultiplier"
            value: "2000"
          }
        }

**Comment by holme-r** [comment]
TR-181 added this caveat after OBUSPA was released. OBUSPA just hasn't caught up yet.
This is a low priority issue, since a controller would need to understand that Protocol was a discriminator when interpreting the response, regardless of whether the caveat was implemented or not.

**Comment by holme-r** [comment]
Closing as discussion closed.
