### ISSUE TITLE
Getting HandleCliCommandRemotely(178): connect failed error

### ISSUE THREAD

**Issue by M0ulinamary** [BroadbandForum/obuspa#80]
I have tried to setup standalone USP-Agent using Docker. But the obusp command not works.
O/P:
/obuspa# sudo obuspa -c get "Device.DeviceInfo.SoftwareVersion"
**HandleCliCommandRemotely(178): connect failed : (err=2) No such file or directory**

I tried with sudo permission, still same issue.

**Comment by anderewrey** [comment]
Hi,
Is the main process of obuspa running? To use the CLI, you must have obuspa already running in the system.

And if it runs, is it running without errors? You have to provide its default settings, as documented in https://github.com/BroadbandForum/obuspa/blob/master/QUICK_START_GUIDE.md#running-ob-usp-agent-for-the-first-time

**Comment by M0ulinamary** [comment]
Yes obuspa is running. Still i have this issues. Also, i dont see the SSH daemon process running except OBUSPA.

obuspa# docker ps
**CONTAINER ID   IMAGE              COMMAND                  CREATED        STATUS        PORTS                                   NAMES**
50e271eb527c   obuspa:devel-env   "obuspa -v4"             21 hours ago   Up 21 hours   0.0.0.0:2222->22/tcp, :::2222->22/tcp   obuspa-devel
ab3fbb161ec7   obuspa:latest      "obuspa -r /obuspa/f…"   22 hours ago   Up 22 hours                                           condescending_kirch

**Comment by holme-r** [comment]
The CLI commands use the Unix domain socket file /tmp/usp_cli (you can change this in vendor_defs.h).
Within the docker container, start the OBUSPA daemon using sudo, and leave it running. It should be listening on the Unix domain socket file, and can be verified with `sudo netstat -tulpn`. Then (also within the container), perform `sudo obuspa -c Device.DeviceInfo.SoftwareVersion`. This will connect to the running daemon to perform the get.
All the above commands need to be run in the container. Perhaps you are running `obuspa -c` on the host and this is why it is failing ?

**Comment by M0ulinamary** [comment]
Inside Docker Container: ( I hope i have running obuspa process)

root@50e271eb527c:/# ps -aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.1 203380 13408 pts/0    Ssl+ May02   0:14 obuspa -v4
root          24  0.0  0.0   4504  3928 pts/1    Ss   10:16   0:00 bash
root          35  0.0  0.0   8104  3316 pts/1    R+   10:17   0:00 ps -aux

Still need to have anything ?

**Comment by holme-r** [comment]
Right, so the OBUSPA daemon process is running. Now what happens when you run  `sudo obuspa -c Device.DeviceInfo.SoftwareVersion` from within the container ? And if it doesn't work, what does `netstat -tulpn` show ?

**Comment by M0ulinamary** [comment]
root@50e271eb527c:/# obuspa -c Device.DeviceInfo.SoftwareVersion
Running command on database /usr/local/var/obuspa/usp.db
ERROR: Unknown command: Device.DeviceInfo.SoftwareVersion

When i run the below:
root@50e271eb527c:/# obuspa -c get "Device.DeviceInfo.SoftwareVersion"
Device.DeviceInfo.SoftwareVersion =>

I have below queries
1. Is there a way to perform the operations like (Reboot/Factoryreset) ?
2. Other than this, I want to setup Controller to manage the agent. Is there any training links to setup and test the controller to agent relation ? 
3. Where is the controller code setup (like this agent setup) ?

**Comment by holme-r** [comment]
Good, so executing OBUSPA in CLI mode is now working for you.
Get `Device.LocalAgent.SoftwareVersion` if you want to see the version number of the OBUSPA code. `Device>DeviceInfo.SoftwareVersion` is the version of the firmware image and this is a parameter which  you need to implement, hence it's currently an empty string.
1. Use `obuspa -c operate`
2. This depends on which USP Controller you are using. Most are proprietary.
3. There is a test controller on github https://github.com/BroadbandForum/obuspa-test-controller. It is quite limited though, and no substitute for a proper USP Controller.

**Comment by holme-r** [comment]
Closing as the original reported issue has been addressed and questions answered.
