### ISSUE TITLE
Getting " Missin Opening bracket in arguments error"

### ISSUE THREAD

**Issue by M0ulinamary** [BroadbandForum/obuspa#81]
Hi,
I have done Docker setup with Agent and trying to do few operations. But it is not getting complete.

Please help me with correct arguments and command to pass the command(boot). 

Also, let me know what are all the operations available with these on Agent?

**Error:**
root@sdadsadsasd:/# obuspa -c operate boot
Missing opening bracket in the argument
root@sdadsadsasd:/# obuspa -c operate [boot]
Missing opening bracket in the argument
root@sdadsadsasd:/# obuspa -c operate [reboot]
Missing opening bracket in the argument

**Comment by anderewrey** [comment]
You may refer to https://github.com/BroadbandForum/obuspa/blob/master/QUICK_START_GUIDE.md#ob-usp-agent-command-line-arguments

In your case, there's two things:
- the double-quotes (when the arguments must not be interpreted by bash)
- the right TR-369 operation

`obuspa -c operate "Device.Reboot()"`

All the commands must be written in the TR-369 way: https://usp-data-models.broadband-forum.org/tr-181-2-15-1-usp.html#D.Device:2.Device.Reboot().
