### ISSUE TITLE
Reboot() operation on Agent not working.

### ISSUE THREAD

**Issue by M0ulinamary** [BroadbandForum/obuspa#85]
I have done setup of USP Agent in Server A. And done test controller setup in Server B.

All other Get/Set/GetDm commands are working. When i issue the Reboot command, I could see that the request reached to Agent, And response says "Controller initiated reboot". And then the running Agent console stopped, No restart happened . 

Can you help to debug on why the stop happening, and Start is not taking place ? How to test the reboot completely with Agent (Controller initiated Reboot) ?

**Actual result in Agent:**
**Request:**
header {
  msg_id: "101"
  msg_type: OPERATE
}
body {
  request {
    operate {
      command: "Device.Reboot()"
      command_key: "boot123"
      send_resp: true
    }
  }
}

**Response:**
header {
  msg_id: "101"
  msg_type: OPERATE_RESP
}
body {
  response {
    operate_resp {
      operation_results {
        executed_command: "Device.Reboot()"
        req_output_args {
        }
      }
    }
  }
}

Disconnecting from (host=agent.com, port=61613)
**Performing Controller initiated Reboot.**

Stop happened, No start is happening. Please help here.

**Comment by anderewrey** [comment]
Hello,

You have to implement your "Reboot" handling in your own vendor file.
Once you wrote your own "Reboot" function, you have to give its callback to obuspa.

````
  vendor_hook_cb_t vendor_hook_cb = {nullptr};
  vendor_hook_cb.reboot_cb = Reboot;
  vendor_hook_cb.factory_reset_cb = FactoryReset;
  usp_err = USP_REGISTER_CoreVendorHooks(&vendor_hook_cb);
````
where both `Reboot` and `FactoryReset` are function names.

See https://github.com/BroadbandForum/obuspa/blob/master/src/include/usp_api.h#L260

**Comment by holme-r** [comment]
Also see https://github.com/BroadbandForum/obuspa/blob/master/QUICK_START_GUIDE.md#overriding-the-core-implementation

**Comment by johnblackford** [comment]
Question Answered - please re-open if this is still an issue
