### ISSUE TITLE
Notify message not fired from USPAgent

### ISSUE THREAD

**Issue by M0ulinamary** [BroadbandForum/obuspa#86]
I want to trigger Events (Boot/Periodic/Push) from Agent to Controller.

Already there is 1 Queue (/agent/queue) published by Agent and Subscribed by Controller. Now, i want to know how to trigger/notify these messages from Agent to Controller ? Any reference for this ?

Do we simply need to add any specific parameters in Factory_reset.txt itself ?? or do we need to update the code inside agent ? If so, could you please guide me on the initial steps to test ?

**Comment by holme-r** [comment]
You need to have a subscription to the event in the Subscription table. See
https://usp-data-models.broadband-forum.org/tr-181-2-15-1-usp.html#D.Device:2.Device.LocalAgent.Subscription.{i}.
