### ISSUE TITLE
Unable to get response for SET command

### ISSUE THREAD

**Issue by M0ulinamary** [BroadbandForum/obuspa#89]
Hi,

I am trying to set value for PeriodicInforNotif parameter from Controller. Default periodic is working with 60 sec. I want to change the value to 120.

**Command in Executing file in Controller:**

msg_id:"101" to_id:"proto::AgentA" stomp_agent_dest:"/queue/controller-notify-dest" stomp_instance:"1"
**msg_type:"Set"** update_objs{obj_path:"**Device.LocalAgent.Controller.1.**" {**param:"PeriodicNotifInterval" value:"120"**}}

But, getting the below error. Could you please help ?

**Error on Agent:**
header {
  msg_id: "101"
  msg_type: SET_RESP
}
body {
  response {
    set_resp {
      updated_obj_results {
        requested_path: "Device.LocalAgent.Controller.1."
        oper_status {
          oper_success {
            updated_inst_results {
              affected_path: "Device.LocalAgent.Controller.1."
              param_errs {
                param: "**PeriodicNotifInterval**"
                **err_code: 7003
                **err_msg: "DATABASE_SetParameterValue(569): sqlite3_step failed (err=1032) attempt to write a readonly database"****
              }
            }
          }
        }
      }

Please help here to solve this issue

**Comment by holme-r** [comment]
"attempt to write a readonly database" usually occurs due to permission errors. Perhaps the database was created as root, and you are not now running as root ?

**Comment by holme-r** [comment]
For the "attempt to write a read only database" issue, if you're using the /tmp directory to store your USP DB then one possible cause might be: https://unix.stackexchange.com/questions/691441/root-cannot-write-to-file-that-is-owned-by-regular-user

**Comment by holme-r** [comment]
Closing as there has been no comments for a while. Please re-open if there are any further comments.
