### ISSUE TITLE
USP Agent - Datamodel Thread Watchdog

### ISSUE THREAD

**Issue by shanthakumarks** [BroadbandForum/obuspa#90]
Hi ,

We are trying to implement a watchdog process/thread to monitor the datamodel thread.  If USP Agent process itself is killed, we have a mechanism in place to respawn the USP Agent process again. Now we are working on implementing a mechanism to monitor the datamodel thread. What if the datamodel thread gets busy/stuck in the vendor get/set callback functions and the control never comes back to the datamodel thread. In this case, the datamodel thread will not able to handle any new requests that come from USP Controller. 
Wondering if we have any mechanism already is in place to handle such scenarios in OBUSPA core code. Appreciate your suggestions .

**Comment by holme-r** [comment]
Sorry but OBUSPA does not have any watchdog mechanisms. Watchdog mechanisms tend to be very specific to the system in which OBUSPA runs, can add a lot of complexity and require a lot of tuning to get right, consequently there are currently no plans to add watchdog functionality to the OBUSPA core code. You could add the mechanism in your vendor layer e.g. the get/set vendor hooks if you are worried about those locking up.
