### ISSUE TITLE
Ping count is not reseted after the ALLOWED_MISSING_PONGS threshold is reached

### ISSUE THREAD

**Issue by s-srakshe** [BroadbandForum/obuspa#97]
Once the ping count becomes > ALLOWED_MISSING_PONGS, then the current connection is closed and a new connection is created after some time. But since the ping count is still > ALLOWED_MISSING_PONGS, the new connection is closed immediately and the cycle repeats forever. This way the connections are continuously created and then closed immediately. 

https://github.com/BroadbandForum/obuspa/blob/master/src/core/wsclient.c#L2076

ping count must be reseted to 0 after reaching the value of ALLOWED_MISSING_PONGS.

**Comment by holme-r** [comment]
Thanks for finding this issue. The fix is to reset the ping failure count upon reconnection in AttemptWsClientConnect(). The fix should be available in the repo in the next week.

**Comment by holme-r** [comment]
Closing as the fix is now available in v7.0.5 on master branch.

**Comment by s-srakshe** [comment]
Thanks for the fix.
