### ISSUE TITLE
ValueChange trigger clarification

### ISSUE THREAD

**Issue by Wonderjack996** [BroadbandForum/obuspa#98]
Hello everyone.

I'am now to ob-usp-a, and i've not understand very well how can i trigger a ValueChange notification.

There is not a way to signal that like we do with the event?

Thanks to everyone.

**Comment by holme-r** [comment]
The current mechanism has the parameters selected by the Value Change subscription being polled at a rate of VALUE_CHANGE_POLL_PERIOD (default: 30 seconds). If any have changed since the last poll period, then a ValueChange notification is sent.

**Comment by Wonderjack996** [comment]
Ok, thank you. Now i've understand how i work. But, it's possible to do that only with DBParam, or also with VendorParam?

**Comment by Wonderjack996** [comment]
Thank you. I've tried and i receive the notification (after making a correct subscription).
